### ISSUE TITLE
virtualenv nesting warning

### ISSUE THREAD

**Issue by TrackerSB** [PolyJIT/benchbuild#137]
Throw a warning when a project uses virtualenv while benchbuild is installed within a virtualenv *whenever* virutalenv(...) is called.

**Comment by simbuerg** [comment]
That should not be a problem. The virtualenv is never 'activated' we just use the python interpreter inside the virtualenv to install lnt into a separate prefix. What is the root-cause
that makes you believe that it is an issue with virtualenv?

**Comment by TrackerSB** [comment]
There are exactly 5 projects which have thrown an error like "cc1 binary not found". These are exactly the projects of lnt which are the only once using virtualenv.
When benchbuild is installed within a virtualenv the error arises on every project in lnt.
When benchbuild is installed directly on the system it does *not*.

**Comment by simbuerg** [comment]
I successfully conduct measurements using a venv-installed benchbuild for years now, that's why I doubt that the venv suddenly becomes a problem.

**Comment by TrackerSB** [comment]
For me it actually really sounds like a virtualenv problem. What else have these five projects in common? What could it be that no other project has this problem?
