### ISSUE TITLE
'cp'-Adjustment for MacOS

### ISSUE THREAD

**Issue by tobiH94** [PolyJIT/benchbuild#208]
- `-ar`: Stderr:  | cp: the -R and -r options may not be specified together.
- `--reflink=auto`: Stderr:  | /bin/cp: illegal option -- -

Lösung: `-RL`

**Comment by simbuerg** [comment]
--reflink=auto is not equivalent to -L.

--reflink will try to use copy-on-write.
This removes the space usage for any downloaded source file that is copied into the build directory, if it is on the same filesystem.

-a provides more than just -R.

Your suggestion will not result in equivalent behavior. I have no MacOS to test/look into it. You need to find options that mimic at least -a. The reflink is not necessary, but can be masked per version of binutils available.

**Comment by tobiH94** [comment]
If `-p` is also specified, all metadata is also transferred. The command even works on Linux and Mac.
This should be the same as `-a`?

`--reflink` is simply not available on Mac, just like all other long options with `--`. Also there is no other option for doing the same.

**Comment by simbuerg** [comment]
From the manpage of cp:

> -a, --archive
>               same as -dR --preserve=all
> -p     same as --preserve=mode,ownership,timestamps
> -d     same as --no-dereference --preserve=links
>
