### ISSUE TITLE
Exception during project loading due to missing URL

### ISSUE THREAD

**Issue by boehmseb** [PolyJIT/benchbuild#239]
Since today, any call to benchbuild causes the following exception:
```
../../.venvs/benchbuild/lib/python3.8/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
benchbuild/projects/gentoo/__init__.py:13: in <module>
    from . import autoportage
benchbuild/projects/gentoo/autoportage.py:5: in <module>
    from benchbuild.projects.gentoo.gentoo import GentooGroup
benchbuild/projects/gentoo/gentoo.py:28: in <module>
    class GentooGroup(project.Project):
benchbuild/projects/gentoo/gentoo.py:34: in GentooGroup
    VERSION = CONTAINER.version
benchbuild/utils/container.py:22: in call_or_cache
    ret = func(*args, **kwargs)
benchbuild/utils/container.py:96: in version
    _version = datetime.utcfromtimestamp(int(_version))\
E   ValueError: invalid literal for int() with base 10: '<html><head>'
```

The cause is that the following url is currently not existant: http://distfiles.gentoo.org/releases/amd64/autobuilds/stage3-amd64.txt (cf. class Gentoo in container.py).
However I am not sure whether this is a temporary issue or not.

**Comment by vulder** [comment]
This currently breaks everything that imports BB because the bug is triggered during auto discover.

**Comment by vulder** [comment]
Ok it seems like the URL is up again and everything is back to normal. But I guess we should add something to BB that prevents it from crashing when a URL is not avail.

**Comment by simbuerg** [comment]
Ooof. I think it will be an easy fix, as soon as container support is in. There is no need for the gentoo group as soon as that is done.

In the meantime, you can disable loading gentoo projects by removing them from the list of project
plugins.
BB_PLUGINS_PROJECTS is the relevant env var. Alternatively, remove it from your .benchbuild.yml.

**Comment by vulder** [comment]
Nope, the plugins are default removed for vara.
This triggers in the python parsing step in __INIT__

But now that the website is online again we do not have any problems, so
waiting for cont. support release is fine.
