### ISSUE TITLE
pathos missing from setup.py 

### ISSUE THREAD

**Issue by boehmseb** [PolyJIT/benchbuild#277]
The `pathos` package is only contained in requirements.txt, but not in setup.py, so it does not get installed when installiing benchbuild via pip.

**Comment by simbuerg** [comment]
https://github.com/PolyJIT/benchbuild/pull/273/files

It was included in the PR. Let me check where I lost it. Probably one of the automatic merge conflict resolutions on github prs

**Comment by simbuerg** [comment]
Hmm that is strange. I would expect that github would report a merge conflict. However, PR #273 and PR #274 both touch setup.py and the version of PR#274 wins. Both have the same ancestor, even more reason to result in a merge conflict.

**Comment by vulder** [comment]
I had the same problem. I found the dep in setup.py on master and tried to merge updates into @boehmseb branch but then this happend:
```
> git merge master
Already up to date.
```

**Comment by simbuerg** [comment]
fixed in 1cdac994c43379cea98163ed8ac578ccd2dcf73a
