### ISSUE TITLE
unique violation, key already exists

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#42]
tests: lapack, ludcmp, minisat, stage3, syrk, heat-3d

Stderr:  | terminate called after throwing an instance of 'pqxx::unique_violation'
         |   what():  ERROR:  duplicate key value violates unique constraint "metrics_pkey"
         | DETAIL:  Key (name, run_id)=(pprof.dyncov, 1245646) already exists.
         | 
srun: error: chimaira04: task 0: Exited with exit code 1

**Comment by simbuerg** [comment]
Fixed in 2.0.x releases
