### ISSUE TITLE
Benchbuild cannot unpickel compiler

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#514]
Benchbuild crashes when trying to unpickl the generated compiler wrapper during an experiment run.

This script reproduces the bug with the current benchbuild version 6.4 on a debian 11 maschine running python3.9.
```
#!/usr/bin/env bash

mkdir testsetup
virtualenv -p python3 testsetup/virt
cd testsetup
source virt/bin/activate
pip install benchbuild
source virt/bin/activate
BB_CLEAN=false benchbuild -vv run -E raw -G benchbuild x264
./results/raw/x264-benchbuild@b093bbe7d9,tbbt-small,sintel/clang --help
```

**Comment by simbuerg** [comment]
Thanks, could reproduce it on my end.
