### ISSUE TITLE
ContainerImage.from_ does not normalize base image name with oci_compliant_name()

### ISSUE THREAD

**Issue by boehmseb** [PolyJIT/benchbuild#544]
This leads to lookup failures when looking up using a non-comliant name that was previously used for creating an image.

**Comment by simbuerg** [comment]
I need an example of this happening. The Image model will not do any validation by itself. The default way is to use a command to create an image, which will sanitize the name.

**Comment by boehmseb** [comment]
I automatically create a stack of container images that successively depend on each other.
Therefore, I have a function that creates the names for each container. Now let's say this function creates names that are not entirely OCI compliant (they contain uppercase letters).
I create container image A with such a name which works fine because the `CreateImage` command normalizes the image name with `oci_compliant_name()`.
However, for the next image, I start with `ContainerImage.from_()` with that same (incompliant) image name as before.
Now, buildah does not find the requested image because it does _not_ normalize the image name as before.

**Comment by simbuerg** [comment]
What prohibits you from using CreateImage on the second image?

**Comment by boehmseb** [comment]
I do eventually pass the second image to the `CreateImage` command, that isn't the problem.
The issue is that the second image is based on the first one, meaning that the first layer of the second image is created with `ContainerImage.from_(<first_image>)`.
The issue is that the name `<first_image>` is different from the actual image name if it is not an OCI compliant name because it does not get normalized.
This means that the `CreateImage` will fail becaus it cannot find any image with the name `<first_image>`.
